name: short fuzz on the power arch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-20.04
    name: Build on ubuntu-20.04 ppc64le
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        env:
          DEBIAN_FRONTEND: noninteractive
        with:
          arch: ppc64le
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            apt-get -qq update
            apt-get install -q -y clang cmake git wget zip ninja-build
            wget --quiet https://dl.bintray.com/pauldreik/simdjson-fuzz-corpus/corpus/corpus.tar
            tar xf corpus.tar && rm corpus.tar
            fuzz/build_like_ossfuzz.sh
            mkdir -p common_out
            for fuzzer in build/fuzz/fuzz_* ; do echo $fuzzer;$fuzzer common_out out/* -max_total_time=40; done

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"

